### ISSUE TITLE
trying to use the comand line tool but I getting a error

### ISSUE THREAD

**Issue by fsvieira** [ricardogsilva/LSASAF-georeferencer#4]
I am trying to use the command line tool, I tried the ui tool and it works perfect but  when I try the command line tool I get this error:

../../LSASAF-georeferencer/georef_hdf5.py -o test/ -v HDF5_LSASAF_MSG_LST_Euro_201303030245
INFO:root:Starting execution...
DEBUG:root:georefsDir: test/georefs
DEBUG:root:warpedDir: test/
DEBUG:root:projectionString: +init=epsg:4326
DEBUG:root:fileList: ['HDF5_LSASAF_MSG_LST_Euro_201303030245']
DEBUG:root:Creating directory: test/
DEBUG:root:Creating directory: test/georefs
DEBUG:root:Processing file HDF5_LSASAF_MSG_LST_Euro_201303030245...
DEBUG:H5Georef:lon: -2.64505261571
DEBUG:H5Georef:lat: 58.7456182082
Traceback (most recent call last):
  File "../../LSASAF-georeferencer/georef_hdf5.py", line 95, in <module>
    options.projectionString)
  File "../../LSASAF-georeferencer/georef_hdf5.py", line 65, in main
    samples = h5g.get_sample_coords()
  File "/mnt/data/scripts/lst_projecto/LSASAF-georeferencer/h5georef.py", line 115, in get_sample_coords
    easting, northing = self._get_east_north(lon, lat)
  File "/mnt/data/scripts/lst_projecto/LSASAF-georeferencer/h5georef.py", line 130, in _get_east_north
    os.chdir(os.path.dirname(self.h5FilePath))
OSError: [Errno 2] No such file or directory: ''

**Comment by ricardogsilva** [comment]
Hello
Thanks for the bug report. I am currently on holiday (visiting the Azores archipelago). I'll be back in the beginning of September. I'll take a look at it then.

Best regards

**Comment by allo0** [comment]
Same problem here.
Do we have any update on the issue?

**Comment by ricardogsilva** [comment]
Hi @allo0 

This is an old project, which I've not been able to maintain, since I'm no longer working with LSASAF data.

I've been meaning to give it an update since some years now, but still haven't gotten around to doing it. Unfortunately I cannot promise you any date for when it might be updated.

I suggest you get in contact with the LSASAF team about your use case. They'll likely help you out more promptly.

**Comment by allo0** [comment]
@ricardogsilva 
Found a temporary workaround.
Just commenting out the  ```os.chdir(os.path.dirname(self.h5FilePath))``` 
in the h5georef.py line 130, did the trick
 ```python
        oldDir = os.getcwd()
        # os.chdir(os.path.dirname(self.h5FilePath))
```
